### ISSUE TITLE
Badge only shows a yellow ! No updates

### ISSUE THREAD

**Issue by hellomrjones** [mediabounds/streamdeck-jira#1]
I use a non-cloud set up with my company, where I created a API Token in my profile and set it up accordingly.
Instead of no. of issues found for the jql query, I only ever get a yellow "!". I don't know where to check errors or anything.

**Comment by hellomrjones** [comment]
When Checking the "My API tokens" it tells me it was never accessed.

**Comment by mediabounds** [comment]
The yellow ! means that some error was encountered during the network request to get issues. It can also appear if the JQL query was invalid.

I would first suggest double checking that...
* the domain is correct (no `https://` at the front and no trailing slashes at the end)
* the email address is the correct email address for the API token
* the API token doesn't have an extra space at the end
* the JQL query is valid

If everything looks good there, then we need to look at Stream Deck's logs. The plugin will log error messages to the Stream Deck log. Logs are saved to disk per plugin in the folder ~/Library/Logs/StreamDeck/ on macOS and %appdata%\Elgato\StreamDeck\logs\ on Windows.

You're welcome to post the full log files here--but you might want to search through it first to see if any other plugins logged information you don't want to post.

I only have access to Jira Cloud and haven't tested this with an Jira Server/on-prem -- so hopefully there's not some limitation.

**Comment by hellomrjones** [comment]
Thanks for the swift reply.
I checked all of the above. 

This is the message getting repeated in the log:
11:50:53.7619 [Query] Received error while updating response: Unexpected token < in JSON at position 11

Doesn't give me much more insight, any idea? Thank you.

**Comment by hellomrjones** [comment]
I guess it's connected to this found in the StreamDeck0.log

09:25:57.5718          static std::string EGQTCredentialStore::GetPasswordWithServerAndUserName(): Failed to read in Keychain com.elgato.StreamDeck.com.mediabounds.streamdeck.jira due to error -25300

**Comment by mediabounds** [comment]
Hm--doesn't give me much insight either.
But it does tell me that I need to improve error reporting. Give me a couple days and I'll prepare a beta version that improves visibility of the error messages. If you're willing to test that beta version, that will hopefully at least clarify _why_ you're getting an error.

**Comment by hellomrjones** [comment]
I could imagine that my company setup of JIRA needs further authentication maybe? I can't set a password in the settings though. I'm happy to test it with you as I'm absolute keen in populating my StreamDeck with any JIRA/Confluence monitors I can.

**Comment by mediabounds** [comment]
I've just posted a beta version of the plugin that improves error reporting:
https://github.com/mediabounds/streamdeck-jira/suites/10648388697/artifacts/532027288

<details>
  <summary>Installing a debug plugin</summary>

  Unzip the file from the link above. It will contain a single file: `com.mediabounds.streamdeck.jira.streamDeckPlugin`

  When you launch it, Streamdeck will confirm that you want to install this plugin from the Internet:
  <img width="532" alt="Screenshot 2023-01-29 at 1 35 57 PM" src="https://user-images.githubusercontent.com/480718/215351741-531ba25a-2909-4cb8-a34a-6188b944fb9b.png">

  Clicking **Install** will upgrade the version you installed from the Streamdeck store to this beta version.

  For transparency sake: all builds are produced by GitHub so you can see exactly what changed from the last version submitted to Elgato.
</details>

With this version, there is now a status indicator in the Property Inspector:
<img width="283" alt="Screenshot 2023-01-29 at 1 31 58 PM" src="https://user-images.githubusercontent.com/480718/215351493-5c434029-70b3-4e24-a009-1da0985e2955.png">

If there is something wrong (and a yellow ! appears on the icon) then the status indicator will change to:
<img width="274" alt="Screenshot 2023-01-29 at 1 32 12 PM" src="https://user-images.githubusercontent.com/480718/215351522-828da715-75b0-4cb1-9119-9f8ba85cec8e.png">

Clicking on the status indicator will show a high-level reason for the problem:
<img width="428" alt="Screenshot 2023-01-29 at 1 32 26 PM" src="https://user-images.githubusercontent.com/480718/215351547-94f99afc-13a6-4b69-a772-3d03e37950df.png">

Alt-clicking (i.e. right-clicking) on the status indicator will show a debug window with the response that was received from the server:
<img width="515" alt="Screenshot 2023-01-29 at 1 32 49 PM" src="https://user-images.githubusercontent.com/480718/215351571-358f9c6d-c617-48c1-add2-071619b4f90d.png">

Would you be willing to try out this version and see what the debug window shows? I'm hoping this will lead us to the root cause about why the plugin doesn't work for you.

**Comment by hellomrjones** [comment]
Thanks! And this are the results:

![Screenshot 2023-01-30 at 08 21 44](https://user-images.githubusercontent.com/31282611/215413729-702b2c8a-b530-43dd-a4ba-7073469999e2.png)



connection	Keep-Alive
content-security-policy	frame-ancestors 'self'
content-type	text/html;charset=UTF-8
date	Mon, 30 Jan 2023 07:28:59 GMT
keep-alive	timeout=5, max=100
referrer-policy	strict-origin-when-cross-origin
server	Apache Tomcat
strict-transport-security	max-age=16070400; includeSubDomains, max-age=31536000
transfer-encoding	chunked
www-authenticate	OAuth realm="https%3A%2F%2Fjira.REDACTED.com"
x-anodeid	backend1
x-arequestid	508x1345592x1
x-content-type-options	nosniff
x-frame-options	allow-from https://jira.REDACTED.com/
x-seraph-loginreason	AUTHENTICATED_FAILED
x-xss-protection	1; mode=block

**Comment by mediabounds** [comment]
Okay, that helps--looks like there is a difference between Jira Cloud and Jira Server here.

The plugin uses Basic authentication -- which Jira Cloud supports with something called [API tokens](https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/).

Apparently Jira Server does not have the same thing (there is something called [Personal access tokens](https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html), but its different).

Based on [the documentation](https://developer.atlassian.com/server/jira/platform/basic-authentication/) for Jira Server, it looks like it _does_ support Basic authentication, but in the field for *API token*, you should enter your Jira password.

Are you able to see if that works?

**Comment by hellomrjones** [comment]
It sadly doesn't help. Probably will not ever work with company wide single sign on in between, where I'd also would have to provide a 2FA Code in order to enter. Thanks for looking into it.

**Comment by mediabounds** [comment]
I'm going to look into supporting Personal Access Tokens. Based on the documentation, it doesn't seem like it'll be too challenging and hopefully it'll help others on Jira Server.

**Comment by mediabounds** [comment]
I just pushed up an updated beta with a (very) preliminary test to see if I'm on the right track with Personal Access Tokens:
https://github.com/mediabounds/streamdeck-jira/suites/10677171564/artifacts/534097449

There is a new drop-down in the property inspector to toggle between Jira Cloud and Jira Server. You'll want to select Jira Server and make sure you have a Personal Access Token as described here:
https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html
<img width="297" alt="Screenshot 2023-01-30 at 9 26 17 PM" src="https://user-images.githubusercontent.com/480718/215655416-4a89e3c3-1ee5-44c3-b984-99caa1a6c28e.png">

I have no way of testing this myself -- so I hope you don't mind give this a shot and letting me know the outcome.

**Comment by Rigidoont** [comment]
Hi! I have the same issue, and I just tried your updated beta. Sadly, it doesn't work and here's the error message when I click on "Something is not right":
![image](https://user-images.githubusercontent.com/28358560/215720860-95ad8369-1698-4591-8d64-62572170ca08.png)

I made sure to select "Jira Server" and provided the correct Personal Access Token.

I also tried Alt-clicking and right-clicking the status indicator, but it always opens a dialog with the same message (screenshot above). I'm using Windows.

**Comment by mediabounds** [comment]
Thanks for the feedback @Gidoont -- curiously, it seems like your server is _saying_ the response was successful, but then not providing the data we asked for. I just updated the beta build to try and handle this scenario so you get better debug data:
https://github.com/mediabounds/streamdeck-jira/suites/10687778087/artifacts/534877192

If alt-clicking the status indicator still doesn't do anything, check the logs at `%appdata%\Elgato\StreamDeck\logs\` to see if there's more information there.

Thanks for debugging with me!

**Comment by Rigidoont** [comment]
Great! Right-clicking status indicator works now, here's a screenshot:
![223__31 01 2023_17 12 34__StreamDeck](https://user-images.githubusercontent.com/28358560/215787248-2c847e6b-6c08-4767-b117-ee691aab504f.png)


Also, message displayed on the left-click has changed:
![221__31 01 2023_17 11 19__StreamDeck](https://user-images.githubusercontent.com/28358560/215787334-1ab65321-f34c-4cdc-a8b8-66a7746f2f84.png)



<details>
  <summary>Here's the full text of it:</summary>
<pre>Log into Atlassian - Jira
var AJS=AJS110;AJS.debug=true;
(function() {
var contextPath =
function printDeprecatedMsg0 {
if (console &amp;&amp; console.warn) {
console.warnCDEPRECATED JS - contextPath global variable has been deprecated since 7.4.0. Use •wrm/context-path& module instead.');
Object.defineProperty(window, •contextPath', {
get: function0 {
printDeprecatedMsg0;
return contextPath;
set: function(value) {
printDeprecatedMsg0;
contextPath = value;
window.WRM=window.WRMll{};window.WRM._unparsedData=window.WRM._unparsedDatall
0;window.WRM._unparsedErrors=window.WRM._unparsedErrorsll{};
\&quot;&quot;;
WRM._unparsedData[&quotjira.core:feature-flags-data.feature-flag-data&quot;]=&quot;{\&quot;enabled-feature-keys\&quot;:
[\&quot;com.atlassian.jira.agile.darkfeature.editable.detailsview\&quot;,\&quot;nps.survey.inline.dialog\&quot;,
\&quot;com.atlassian.jira.agile.darkfeature.edit.closed.sprint.enabled\&quot;,\&quotjira.plugin.devstatus.phasetwo\&quot;,
\&quotjira.frother.reporter.field\&quot;,\&quot;atlassian.rest.xsrf.legacy.enabled\&quot;,\&quotjira.issue.status.lozenge\&quot;,
\&quot;public.access.disabled\&quot;,\&quot;com.atlassian.jira.config.BlG_PlPE\&quot;,\&quot;com.atlassian.jira.projects.issuenavigator\&quot;,
\&quot;com.atlassian.jira.config.PDL\&quot;,\&quotjira.plugin.devstatus.phasetwo.enabled\&quot;,\&quot;atlassian.aui.raphael.disabled\&quot;,
\&[quot;app-switcher.new](http://quot%3Bapp-switcher.new/)\&quot;,\&quot;frother.assignee.field\&quot;,\&quot;com.atlassian.jira.projects.ProjectCentricNavigation.Switch\&quot;,
\&quot;sd.internal.base.off.thread.on.completion.events.enabled\&quot;,\&quotjira.onboarding.cyoa\&quot;,
\&quot;sd.slavalue.record.updated.date.enabled\&quot;,\&quot;com.atlassian.jira.agile.darkfeature.kanplan.enabled\&quot;,
\&quot;com.atlassian.jira.config.ProjectConfig.MENU\&quot;,\&quot;com.atlassian.jira.projects.sidebar.DEFER_RESOURCES\&quot;,
\&quot;com.atlassian.jira.agile.darkfeature.kanplan.epics.and.versions.enabled\&quot;,
\&quot;com.atlassian.jira.agile.darkfeature.sprint.goal.enabled\&quot;,\&quotjira.zdu.admin-updates-ui\&quot;,\&quotjira.zdu.jmx-
monitoring\&quot;,\&quot;sd.sla.improved.rendering.enabled\&quot;,\&quot;sd.canned.responses.enabled\&quot;,
\&quot;mail.batching.enabled\&quot;,\&quot;sd.new.settings.sidebar.location.disabled\&quot;,\&quotjira.zdu.cluster-upgrade-state\&quot;,
\&quot;com.atlassian.jira.email.templates.readFromJiraHome\&quot;,\&quot;com.atlassian.jira.agile.darkfeature.splitissue\&quot;,
\&quot;com.atlassian.jira.config.CoreFeatures.LlCENSE_ROLES_ENABLED\&quot;,\&quotjira.export.csv.enabled\&quot;],\&quot;feature-flag-
states\&quot;:{\&quot;com.atlassian.jira.agile.darkfeature.handle.ug.usernames\&quot;:true,
\&quot;com.atlassian.jira.security.endpoint.non.admin.access.screens\&quot;:false,
\&quot;sd.automation.then.action.edit.issue.custom.fields\&quot;:true,\&quot;sd.custom.email.stripping.rules\&quot;:false,
\&quot;com.atlassian.jira.webhookEventsAsyncProcessing\&quot;:false,\&quot;com.atlassian.jira.serAllowShareWithNonMember\&quot;:true,
& uot•sd.confluence.redirect.with.•wt.token.a ent & uot•:true & uot:com.atlassian.•ira.issuetable.move.links.hidden & uot•:true
\&quot;sd.automation.then.webhook.custom.payload\&quot;:true,\&quot;sd.use.search.by.permissions\&quot;:true,
\&quot;com.atlassian.jira.security.endpoint.anonymous.access.resolution\&quot;:false,
\&quot;com.atlassian.jira.agile.darkfeature.sprint.goal\&quot;:false,\&quot;sd.automation.ruleset.cache\&quot;:true,
\&quot;sd.confluence.cloud.integration\&quot;:true,\&quotjira.cluster.monitoring.show.offline.nodes\&quot;:true,
\&quot;sd.kb.cloud.always.primary\&quot;:false,\&quot;com.atlassian.jira.commentReactions\&quot;:true,
\&quot;sd.approval.requested.when.handler\&quot;:true,\&quot;com.atlassian.jira.custom.csv.escaper\&quot;:true,
\&quot;com.atlassian.jira.fixedCommentDeletionNotifications\&quot;:true,\&quot;com.atlassian.jira.allThumbnailsDeferred\&quot;:false,
\&quot;com.atlassian.jira.plugin.issuenavigator.filtersuxlmprovment\&quot;:true,\&quotjira.customfields.cleanup.identification\&quot;:true,
\&quot;com.atlassian.jira.defaultValuesForSystemFields\&quot;:true,\&quot;sd.queue.react.table\&quot;:true,
\&quot;sd.automation.then.action.archive.issue\&quot;:true,\&quot;sd.customerportal.sla.customer.visibility\&quot;:true,
\&quotjira.customfields.bulk.delete\&quot;:true,\&[quot;sd.email.analytics.open](http://quot%3Bsd.email.analytics.open/)\&quot;:false,
\&quot;com.atlassian.jira.returnDefaultAvatarsForBrokenAvatars\&quot;:true,\&quot;sd.kb.cloud.allow.http\&quot;:false,
\&quotjira.jql.suggestrecentfields\&quot;:false,\&quot;com.atlassian.jira.gdpr.rtbf\&quot;:true,
\&quot;com.atlassian.jira.security.xsrf.session.token\&quot;:true,\&quot;sd.dismiss.all.misconfiguration.warnings.setting\&quot;:true,
\&quot;com.atlassian.jira.security.project.admin.revoke.with.application.access\&quot;:true,\&quot;com.atlassian.jiranomenclature\&quot;:true,
\&quot;com.atlassian.jira.security.endpoint.non.admin.access.avatar.system\&quot;:false,
\&quot;sd.canned.responses.variable.substitution\&quot;:true,\&quot;com.atlassian.jira.agile.darkfeature.future.sprint.dates\&quot;:true,
\&quotjira.customfields.paginated.ui\&quot;:true,\&quot;insight.db.import.h2.enable\&quot;:false,
\&quot;sd.incident.management.feature.polling\&quot;:true,\&quot;com.atlassian.jira.advanced.audit.log\&quot;:true,
\&quot;sd.automation.then.webhook\&quot;:true,\&quot;sd.priorities.per.project\&quot;:true,\&quot;external.links.new.window\&quot;:true,
\&quot;sd.customer.portal.browse.permission.only\&quot;:true,\&quot;sd.inline.noformat.renderer\&quot;:true,
\&quot;sd.customer.profile.multi.languages\&quot;:true,\&quot;data.pipeline.feature.jira.issue.history.export\&quot;:true,
\&quot;sd.new.settings.sidebar.location\&quot;:true,\&quot;atlassian.cdn.static.assets\&quot;:true,
\&quot;com.atlassian.jira.security.endpoint.non.browse.projects.access.fields\&quot;:false,\&quot;sd.customer.search.post.agent.filtering\&quot;:true,
\&quot;sd.sla.improved.rendering\&quot;:false,\&quot;mail.batching\&quot;:false,\&[quot;sd.kb.cloud.allow.empty.display.name](http://quot%3Bsd.kb.cloud.allow.empty.display.name/)\&quot;:false,
\&quot;com.atlassian.jira.security.endpoint.anonymous.access.priority\&quot;:false,\&quotjira.priorities.per.project.edit.default\&quot;:false,
\&quot;com.atlassian.jira.agile.darkfeature.issues.in.epic.details.view\&quot;:true,\&quot;jira.priorities.per.project.jsd\&quot;:true,
\&quot;sd.email.attachment.stripping\&quot;:false,\&quot;com.atlassian.jira.agile.darkfeature.rapid.boards.bands\&quot;:true,
\&quot;com.atlassian.jira.agile.darkfeature.flexible.boards\&quot;:true,\&quot;com.atlassian.jira.agile.darkfeature.epic.validate.visibility\&quot;:true,
\&quot;com.atlassian.jira.send.email.notifications.to.user.without.application.access\&quot;:false,
\&quot;com.atlassian.mail.server.managers.hostname.verification\&quot;:true,\&quot;sd.automation.then.action.auto.answer.approval\&quot;:true,
\&quot;sd.approvals.notification.email.action\&quot;:true,\&quot;com.atlassian.jira.upgrade.startup.fix.index\&quot;:true,
\&quot;sd.email.attachments.store.duplicates\&quot;:false,\&[quot;sd.customer.notifications.suppress.welcome.email](http://quot%3Bsd.customer.notifications.suppress.welcome.email/)\&quot;:true,
\&quot;sd.sla.fix.timeline\&quot;:false,\&quot;sd.customer.share.default.private\&quot;:true,
\&quot;com.atlassian.jira.security.endpoint.anonymous.access.projectCategory\&quot;:false,\&quotjira.redirect.anonymous.404.errors\&quot;:true,
\&quot;sd.customerportal.card.view\&quot;:true,\&quot;com.atlassian.jira.issuetable.draggable\&quot;:true,
\&quot;sd.email.microsoft.pop.two.line.auth\&quot;:true,\&quot;com.atlassian.jira.attachments.generate.unique.suffix\&quot;:true,
\&quot;sd.customerportal.customization.preview\&quot;:true,\&quot;sd.customer.portal.wysiwyg.editor\&quot;:true,
\&quotjira.version.based.node.reindex.service\&quot;:true,\&quot;sd.attachment.is.viewable.short.circuit\&quot;:true,
\&quot;com.atlassian.jira.security.endpoint.anonymous.access.issueLinkType\&quot;:false,
\&quot;sd.email.channel.custom.oauth.config.supported\&quot;:false,\&[quot;sd.internal.base.off.thread.on.completion.events](http://quot%3Bsd.internal.base.off.thread.on.completion.events/)\&quot;:false,
\&quot;com.atlassian.jira.agile.darkfeature.burnupchart\&quot;:true,\&quotjira.instrumentation.laas\&quot;:false,
\&quot;sd.no.schedule.async.upgrade.tasks\&quot;:true,\&quot;sd.customer.portal.editor.mentions\&quot;:true,
\&quot;sd.approvals.with.insight\&quot;:true,\&quot;mail.batching.user.notification\&quot;:true,
\&quot;com.atlassian.portfolio.permission.check.for.permissions\&quot;:true,\&quot;sd.portal.search.bar.settings\&quot;:true,
\&quot;sd.sla.auto.fix.metric\&quot;:true,\&quot;sd.sla.audit.log.smart.cleanup\&quot;:true,\&quot;com.atlassian.jira.issues.archiving\&quot;:true,
\&quot;sd.automation.if.condition.comment.primary.action\&quot;:true,\&quotjira.priorities.per.project\&quot;:true,
\&quot;com.atlassian.jira.use.same.site.none.for.xsrf.token.cookie\&quot;:true,
\&quot;com.atlassian.jira.mailHandlerlmapMessageQueryLegacy\&quot;:false,\&quot;com.atlassian.jira.diagnostics.perflog\&quot;:true,
\&[quot;sd.event.processing.stop.unnecessary.processing.of.jira.issue.events](http://quot%3Bsd.event.processing.stop.unnecessary.processing.of.jira.issue.events/)\&quot;:false,\&quot;sd.prioritise.agent.role\&quot;:true,
\&quot;com.atlassian.jira.dbr\&quot;:true,\&quot;com.atlassian.jira.agile.darkfeature.legacy.epic.picker\&quot;:false,
\&quot;com.atlassian.jira.agile.darkfeature.unlink.sprints.on.issue.move\&quot;:true,\&quot;sd.incident.management.feature\&quot;:true,
\&quot;com.atlassian.jira.user.dbldBasedKeyGenerationStrategy\&quot;:true,\&quot;sd.signup.email.verification\&quot;:true,
\&quot;sd.language.support.administration\&quot;:true,\&quot;com.atlassian.jira.thumbnailsDeferredGeneration\&quot;:true,
\&quot;sd.automation.psmq.async.executor\&quot;:true,\&quot;data.pipeline.feature.jira.issue.links.export\&quot;:true,
\&quot;com.atlassian.jira.agile.darkfeature.kanplan.epics.and.versions\&quot;:false,\&[quot;com.atlassian.jira.jsd.mobile](http://quot%3Bcom.atlassian.jira.jsd.mobile/)\&quot;:true,
\&quot;data.pipeline.feature.jira.all.exportable.custom.fields\&quot;:true,\&quotjira.dc.cleanup.cluser.tasks\&quot;:true,
\&quot;sd.sla.performance.optimization\&quot;:true,\&quot;sd.cluster.safe.mail.channel.shutdown\&quot;:true,
\&quot;com.atlassian.jira.issues.archiving.filters\&quot;:false,\&quot;mail.batching.override.core\&quot;:true,
\&quotjira.users.and.roles.page.in.react\&quot;:true,\&quot;jira.security.csp.sandbox\&quot;:true,
\&quot;com.atlassian.jira.agile.darkfeature.velocity.chart.ul\&quot;:true,\&quot;insight.index.object.type.reindex.on.failure\&quot;:true,
\&quot;sd.automation.audit.log\&quot;:true,\&[quot;com.atlassian.jira.agile.darkfeature.sprint.auto.management](http://quot%3Bcom.atlassian.jira.agile.darkfeature.sprint.auto.management/)\&quot;:false,
\&quot;sd.workinghours.react.component\&quot;:false,\&quot;com.atlassian.jira.agile.darkfeature.optimistic.transitions\&quot;:true,
\&quot;sd.queue.bulk.actions\&quot;:true,\&[quot;sd.internal.base.db.backed.completion.events](http://quot%3Bsd.internal.base.db.backed.completion.events/)\&quot;:false,
\&quot;sd.incident.management.allow.http\&quot;:false,\&quot;com.atlassian.jira.agile.darkfeature.kanplan\&quot;:false,
\&quot;com.atlassian.jira.filtersAndDashboardsShareableWithAllGroupsAndRoles\&quot;:true,
\&quot;com.atlassian.jira.agile.darkfeature.edit.closed.sprint\&quot;:false.\&quotjira.create.linked.issue\&quot;:true,
& uot•sd.automation. ro•ect.runasuser.cache & uot::true & uot•sd.custome ortal.c</pre>
</details>

Thank you for developing this plugin, looks very promising!

**Comment by hellomrjones** [comment]
After installing the new version, creating a new API Token and choosing "JIRA Server" I now get this:
![image](https://user-images.githubusercontent.com/31282611/215814000-2f9ab693-5205-44e6-9c4c-0d2e5465120d.png)

And on the Debug:

![Screenshot 2023-01-31 at 17 05 42](https://user-images.githubusercontent.com/31282611/215814810-a86be737-b69d-435a-9dc8-b62177c66c85.png)

**Comment by mediabounds** [comment]
@hellomrjones / @Gidoont Can you both share what version of Jira Server you're on (if you know)?

In both cases, it _seems_ like the personal access token worked: I presume the reason you both blocked out the `x-ausername` field is because it was your user name was displayed there. The only way it would have gotten that is if the PAT did work.

But it seems like the API request fails...in both cases, it seems like it didn't even make it to the API endpoint. So I need to look through the documentation for Jira Server to see if the API endpoint is different than Jira Cloud.

**Comment by mediabounds** [comment]
I did just have an idea -- if you're willing to continue in my path of guess-and-checking, here's an updated beta version:
https://github.com/mediabounds/streamdeck-jira/suites/10693836547/artifacts/535307608

Based on my reading, it sounds like most server instances have a different API version than Jira Cloud.

**Comment by Rigidoont** [comment]
It works!!
![image](https://user-images.githubusercontent.com/28358560/215851658-d53e82ff-c828-4b71-874f-c6290dbbe444.png)

Thank you very much for putting in the effort to address this problem!
My Jira version is v8.20.9.

**Comment by mediabounds** [comment]
Thank you both again for reporting and helping me test this. I've formalized the release and sent it off to Elgato so it should be available on the plugin store in a few days (or available immediately [from the releases page](https://github.com/mediabounds/streamdeck-jira/releases)).

**Comment by hellomrjones** [comment]
Can also confirm it's working! Thanks sooooo much! If you get the time and are interested, same for confluence would be amazing as well! 
Now I will show off this amazing plugin in my stream deck to the whole organisation :)
