### ISSUE TITLE
Custom URL as Action

### ISSUE THREAD

**Issue by martinmolt** [mediabounds/streamdeck-jira#10]
Thank you for this awesome plugin! :)

Would it be possible to allow opening custom URLs (or jira dashboards) as an action?
In my case I would like to open a (jira-)dashboard when clicking on the jira button.

**Comment by mediabounds** [comment]
That's a great idea!

If you'd like to help with testing it, I've got a beta build ready to go with this new feature:
https://github.com/mediabounds/streamdeck-jira/actions/runs/8584299870/artifacts/1391163191

If you've never installed a Stream Deck plugin directly from the Internet, I've put together a short guide: 
[Installing a preview build](https://github.com/mediabounds/streamdeck-jira/wiki/Installing-a-preview-build)

Let me know if you encounter any issues. Otherwise, I expect to update this in the Elgato Marketplace in a few days.

**Comment by martinmolt** [comment]
Amazing, thank you! 
Just tried it out, works perfectly with setting custom URL to open! 

Thank you! :)

**Comment by mediabounds** [comment]
Great! Thanks for confirming! This should get updated in the Elgato Marketplace later this week.
