### ISSUE TITLE
No support for server.com/confluence style URLs

### ISSUE THREAD

**Issue by shipstefan** [mediabounds/streamdeck-jira#9]
My confluence and JIRA server have URL with the following style

server.com/confluence
server.com/jira

Probably the API route is behind a load balancer or proxy.

The current implementation cleans the path behind the domain.

Could you please allow URLs of this style?

**Comment by mediabounds** [comment]
I know it's been months since you've opened this and you've probably found another solution to what you're looking for. But, in case it's still helpful to you or someone else, I have a preview build of the plugin that does allow for a custom context path.

I don't have access to a Jira Server environment that uses custom context paths, however, so I don't know if this works. Maybe you'd be willing to help me test this?

If you'd like to help with testing it, I've got a beta build ready to go with this new feature:
https://github.com/mediabounds/streamdeck-jira/actions/runs/8584537589/artifacts/1391193049

If you've never installed a Stream Deck plugin directly from the Internet, I've put together a short guide: 
[Installing a preview build](https://github.com/mediabounds/streamdeck-jira/wiki/Installing-a-preview-build)

**Comment by leprovokateur** [comment]
I'd like to test this version, but the streamdeck software tells me, that the jira plugin is already installed, whch is true. The version installed is 1.4, I'd expect this version to be of a higher version, which would be used as an upgrade, but apparently this is not the case.

**Comment by mediabounds** [comment]
@leprovokateur -- whoops, you're right -- a new version of the plugin was released shortly after that build was produced. Here's an updated version with a newer version number:

https://github.com/mediabounds/streamdeck-jira/actions/runs/9881608619/artifacts/1688465633

**Comment by leprovokateur** [comment]
Hi, it works great. When is it to be expected to be part of the official version of the plugin?

**Comment by mediabounds** [comment]
Hopefully by the end of the month! I'm aware of one bug I need to work out with it first.
